location = /nvme-of-path {
    return 301 /nvme-of-path/;
}

location /nvme-of-path/api/ {
    proxy_pass http://127.0.0.1:3132;
    include /etc/nginx/proxy.conf;
}

location /nvme-of-path/ {
    alias /home/admin/web/nvme-of-path/public/;
    try_files $uri $uri/ /nvme-of-path/index.html;
}
